; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

global g_ID

f12::
WinGet, g_ID, ID, A
Gui Destroy
Gui Font, s9, Segoe UI
Gui Add, Button, x475 y5 w136 h71 gButtonClose, 关闭
Gui Add, Tab3, x32 y128 w494 h188, 常用符号|系统咨询
Gui Tab, 1
Gui Add, Button, x48 y160 w92 h43 gButton, 电脑
Gui Add, Button, x152 y160 w92 h43 gButton, 电脑
Gui Add, Button, x256 y160 w92 h43 gButton, ❤️
Gui Tab, 2
Gui Add, Button, x48 y168 w106 h43 gButtonToday, 本日日期
Gui Tab

Gui Show, w620 h420, Window
Return

Button:
    WinActivate, ahk_id %g_ID%
    ; Send 电脑
    Send %A_GuiControl%
    Return
ButtonClose:
    gui hide
    Return

ButtonToday:
    WinActivate, ahk_id %g_ID%
    Send %A_YYYY%年%A_MM%月%A_DD%日
    Return

GuiEscape:
GuiClose:
    ExitApp
